spring.application.name=ap2restapi
server.forward-headers-strategy=framework

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Banco em Memória (Mudei o nome para copadb para fazer sentido com o projeto)
spring.datasource.url=jdbc:h2:mem:copadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cria as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no console da sua IDE (ótimo para ver o que o JPA está fazendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
